language: c
sudo: false
os:
    - linux

cache:
  directories:
    - $TRAVIS_BUILD_DIR/*/
    - $HOME/.elan

install:
  # - export TRAVIS_TAG=${TRAVIS_TAG:-bin-$(date +'%Y%m%d-%H%M%S')-$(git log --format=%h -1)}
  - |
    if [ ! -d "$HOME/.elan/toolchains/" ]; then
      curl https://raw.githubusercontent.com/Kha/elan/master/elan-init.sh -sSf | sh -s -- --default-toolchain none -y
    fi
  - source ~/.elan/env
  - mkdir $HOME/scripts || echo ""
  - export PATH="$HOME/scripts:$PATH"
  - cp travis_long.sh $HOME/scripts/travis_long
  - chmod +x $HOME/scripts/travis_long
  - (git status | grep  -e "Changes not staged for commit:"); RESULT=$?
  - if [ $RESULT -eq 0 ]; then git checkout -f HEAD ; fi
  - git clean -d -f -q
  - ./purge_olean.sh
  - rm mathlib.txt || true
  - travis_long lean -v

jobs:
  include:
    - stage: Pre-build-1
      script:
        - travis_long "timeout 2400 leanpkg test" || true

    - stage: Pre-build-2
      script:
        - travis_long "timeout 2400 leanpkg test" || true

    - stage: Test
      script:
        - leanpkg test
        - lean --recursive --export=mathlib.txt src/
        - leanchecker mathlib.txt
      before_deploy:
        - export RELEASE=$(date +'%Y%m%d-%H%M%S')-$(git log --format=%h -1)
        - export TRAVIS_TAG=${TRAVIS_TAG:-bin-$RELEASE}
        - export OLEAN_ARCHIVE=mathlib-olean-$RELEASE.tar.gz
        - export SCRIPT_ARCHIVE=mathlib-scripts-$RELEASE.tar.gz
        - tar -zcvf $OLEAN_ARCHIVE src
        - mv scripts mathlib-scripts
        - tar -zcvf $SCRIPT_ARCHIVE mathlib-scripts
      deploy:
        provider: releases
        overwrite: true
        skip_cleanup: true
        api_key:
          secure: HsAy78hjdJf+jg2yGqD7MWGCn+8K/EceaZ8sZ2U/95Kprmnetc1A5j1T0pgY531pQbjGm6XSbVdn0L0ymuunKo7gIfg3q4+ns6bMCucnxdCrXdJR9/DoUwSLVqJrdFjcigJ58ekMUh1l2g7jIfqJwCAM09FF+dMF09Wh9wVKGK1TYsr6RHZ7NqYlfme6hO+GwBw545NbSHxWEjvNT/8s+T8sMAwMWqjzXm/n/GNUn2TGoRwkwp/BdcQ9V7hKOHX0bbMQXc5RZniVqVnFpnZHx8zTIWJoKnx4HeS5beYN/OcPha6cShqpml3sGaGSUrkWBnQYOzcx28lA4jblYIc84g7lyryLhT2qYB02Fv4C97hyYIppDDdx4Op3NF4IdPqvHazji1pmctWH6muE0z/pJNw5fEX+eNY9djGnexRE8XnVUJigtvh0cUmYRPlb7+6Qza7K6lXzdXflK8TEDYcY9lTHoLw+h8ffFFxKq18yNzvwMoLk9VaA/h2gSCTTjOXrr8s3tLRBNJEjkFWvRAVPaJCbDep5DPf/eK9VEL497xZAfe8YLf1CKlw1ynV7nNb5VB4dPoQFxak/76gDQT/po1l2c/QC4EJe02Degx0+0FG+e2MlY7k/uJb4qndVXdJZQE9DQty0IquHPU0KNISp+VVb7xanh26UtulE/0YdChI=
        file:
          - "$OLEAN_ARCHIVE"
          - "$SCRIPT_ARCHIVE"
        on:
          branch: master
          repo: leanprover-community/mathlib

notifications:
  webhooks:
    - https://leanprover.zulipchat.com/api/v1/external/travis?stream=travis&topic=build-status&api_key=SwF1QzwUWol76dCxsYgwHbI6giN3cxGn
