language: generic

install:
  - LEAN_VERSION="lean-3.3.1"
  - NIGHTLY="nightly-2018-04-02"
  - curl https://github.com/leanprover/lean-nightly/releases/download/$NIGHTLY/$LEAN_VERSION-$NIGHTLY-linux.tar.gz -L | tar xz -C ..
  - export PATH=../$LEAN_VERSION-$NIGHTLY-linux/bin:$PATH

script:
  - leanpkg test
  - lean --recursive --export=mathlib.txt
  - leanchecker mathlib.txt

notifications:
  webhooks:
    - https://leanprover.zulipchat.com/api/v1/external/travis?stream=travis&topic=build-status&api_key=SwF1QzwUWol76dCxsYgwHbI6giN3cxGn
