language: c
sudo: false
os:
    - linux
branches:
  except:
    - /^lean-.*$/

cache:
  directories:
    - $TRAVIS_BUILD_DIR/test/
    - $TRAVIS_BUILD_DIR/src/
    - $HOME/.elan

install:
  - |
    if [ ! -d "$HOME/.elan/toolchains/" ]; then
      curl https://raw.githubusercontent.com/Kha/elan/master/elan-init.sh -sSf | sh -s -- --default-toolchain none -y
    fi
  - source ~/.elan/env
  - mkdir $HOME/scripts || echo ""
  - export PATH="$HOME/scripts:$PATH"
  - cp travis_long.sh $HOME/scripts/travis_long
  - chmod +x $HOME/scripts/travis_long
  - (git status | grep  -e "Changes not staged for commit:"); RESULT=$?
  - if [ $RESULT -eq 0 ]; then git checkout -f HEAD ; fi
  - git clean -d -f -q
  - ./purge_olean.sh
  - rm mathlib.txt || true
  - export LEAN_VERSION=lean-`lean --run scripts/lean_version.lean`

jobs:
  include:
    - env: TASK="check Lean proofs"
      stage: Pre-build-1
      script:
        - travis_long "timeout 2400 leanpkg test" | python scripts/detect_errors.py

    - env: TASK="check Lean proofs"
      stage: Pre-build-2
      script:
        - travis_long "timeout 2400 leanpkg test" | python scripts/detect_errors.py

    - env: TASK="check Lean proofs"
      stage: Test
      script:
        - travis_long "leanpkg test"
        - lean --recursive --export=mathlib.txt src/
        - travis_long "leanchecker mathlib.txt"
        - sh scripts/deploy_nightly.sh

    - env: TASK="check install scripts"
      language: python
      python:
        - "3.6"
      install:
        - git config --add github.oauthtoken $GITHUB_TOKEN
      os:
        - linux
      script:
        - cp scripts/leanpkg-example.toml leanpkg.toml
        - sh scripts/remote-install-update-mathlib.sh --global
        - source $HOME/.profile
        - update-mathlib

    - env: TASK="check install scripts"
      language: sh
      install:
        - git config --add github.oauthtoken $GITHUB_TOKEN
      os:
        - osx
      script:
        - cp scripts/leanpkg-example.toml leanpkg.toml
        - sh scripts/remote-install-update-mathlib.sh
        - source $HOME/.profile
        - update-mathlib

    - env: TASK="check dev scripts"
      sudo: true
      language: python
      python:
        - "3.6"
      install:
        - git config --add github.oauthtoken $GITHUB_TOKEN
      os:
        - linux
      script:
        - cp scripts/leanpkg-example.toml leanpkg.toml
        - cd scripts
        - echo y | bash setup-dev-scripts.sh --global
        - source $HOME/.profile
        - update-mathlib
        - cache-olean
        - cache-olean --fetch

    - env: TASK="check dev scripts"
      language: sh
      install:
        - git config --add github.oauthtoken $GITHUB_TOKEN
      os:
        - osx
      script:
        - cp scripts/leanpkg-example.toml leanpkg.toml
        - cd scripts
        - echo y | bash setup-dev-scripts.sh
        - source $HOME/.profile
        - update-mathlib
        - cache-olean
        - cache-olean --fetch

notifications:
  webhooks:
    - https://leanprover.zulipchat.com/api/v1/external/travis?stream=travis&topic=build-status&api_key=SwF1QzwUWol76dCxsYgwHbI6giN3cxGn
