version: 1.0.{build}
build: off
only_commits:
  files:
    - scripts/*
    - appveyor.yml

environment:
  matrix:
    - PYTHON: "Python36"
      PYTHON_VERSION: "3.6.x"
      PYTHON_ARCH: "32"
    - PYTHON: "Python36"
      PYTHON_VERSION: "3.6.x"
      PYTHON_ARCH: "64"

test_script:
    - sh -c "if [ '%GITHUB_TOKEN%' != '' ]; then git config --add github.oauthtoken %GITHUB_TOKEN%; echo setting up GitHub credentials; else echo no GitHub credentials available; fi"
    - "SET PATH=C:\\Users\\appveyor\\AppData\\Roaming\\Python\\%PYTHON%\\Scripts;C:\\%PYTHON%;C:\\%PYTHON%\\Scripts; %PATH%"
    - sh -c "echo export PATH=\\\"/c/Users/appveyor/AppData/Roaming/Python/%PYTHON%/Scripts:/c/%PYTHON%:/c/%PYTHON%/Scripts:\$PATH\\\" >> $HOME/.profile"
    - "python --version"
    - cp scripts/leanpkg-example.toml leanpkg.toml
    - sh -c "ln -s `which python` `which python`3"
    - sh scripts/remote-install-update-mathlib.sh --branch=%APPVEYOR_REPO_BRANCH%
    - sh -c "source $HOME/.profile; update-mathlib"
    # what if it's already installed?
    - sh -c "scripts/remote-install-update-mathlib.sh --branch=%APPVEYOR_REPO_BRANCH%"
    - sh -c "source $HOME/.profile; update-mathlib"
    - sh -c "rm -rf $HOME/.mathlib"
    - sh -c "rm $HOME/.profile"

    - sh -c "cd scripts; echo y | bash setup-dev-scripts.sh"
    - sh -c "source $HOME/.profile; update-mathlib"
    - sh -c "source $HOME/.profile; cache-olean"
    - sh -c "source $HOME/.profile; cache-olean --fetch"
    # do it again
    - sh -c "cd scripts; echo y | sh setup-dev-scripts.sh"
    - sh -c "source $HOME/.profile; update-mathlib"
    - sh -c "source $HOME/.profile; cache-olean"
    - sh -c "source $HOME/.profile; cache-olean --fetch"
